insert into clients (nombre,lastName,adress,phone,email) values ('Leonardo','Aviles','patito','5545678912','leo@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('Carlos','Alvarez','patito','7889451623','carlos@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('Juan','Arreola','patito','7891255456','juan@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('Martin','Velazquez','patito','6789125545','martin@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('Miguel','Mendez','patito','5545678912','miguel@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('David','Gonzalez','patito','5545627891','david@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('Raul','Arreola','patito','8912554567','raul@gmail.com')
insert into clients (nombre,lastName,adress,phone,email) values ('Oscar','Marquez','patito','5589124567','oscar@gmail.com')
